### ISSUE TITLE
Functionality Checklist

### ISSUE THREAD

**Issue by avarixe** [avarixe/myfifa-vite#4]
- [x] Registration page
- [x] Home page
- [x] Teams page
  - [x] Add Team
- [x] Team page (Dashboard)
  - [x] Current Date Increment
  - [x] Edit Team
  - [x] Remove Team
  - [x] Contract Expiring List
  - [x] Injury List
  - [x] Loan List
  - [x] Last Match
- [x] Players page
  - [x] Add Player
  - [x] Filters
- [x] Analytics
  - [x] Development
    - [x] Table
    - [x] Player status filters
    - [x] OVR/Value toggle
  - [x] Statistics
    - [x] Table
    - [x] Player status filters
    - [x] Competition, Season filters
    - [x] Player breakdown by Season + Competition
- [x] Player page
  - [x] Player Growth
  - [x] Player Timeline
    - [x] Contract
    - [x] Injury
    - [x] Transfer
    - [x] Loan
      - [x] Activate Transfer 
  - [x] Edit Player
  - [x] Retire Player
  - [x] Release Player
  - [x] Remove Player
- [x] Matches page
  - [x] Add Match
  - [x] Filters
- [x] Match page
  - [x] Edit Match
  - [x] Remove Match
  - [x] Match Formation
  - [x] Match Lineup (mobile)
  - [x] Match Timeline
    - [x] Goal
    - [x] Booking
    - [x] Substitution
    - [x] Penalty Shootout
  - [x] Player Formation
    - [x] Caps
    - [x] Lineup OVR
    - [x] Apply Squad
    - [x] Save Lineup to Squad
  - [x] Previous/Next Match link
- [x] Competitions page
  - [x] New Competition
- [x] Competition page
  - [x] Edit Competition
  - [x] Remove Competition
  - [x] Close Competition
  - [x] Table Stages
  - [x] Knockout Stages
  - [x] Highlight champion and team
- [x] Squads page
  - [x] Mobile View
  - [x] Add Squad
  - [x] Update Squad
  - [x] Remove Squad
  - [x] Squad OVR
- [x] Season page
  - [x] Value/OVR change
  - [x] Transfer History
